version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=daitmanish@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  data: {}